tokenisation_algorithms:
  - newmm
  - longest
text_samples:
  short: >-
    คนที่ฝึกภาษาอังกฤษ แม้ว่าต่างคนจะต่างความต้องการ  แต่อย่างหนึ่งที่ดูจะเหมือนกัน คือ
    อยากอ่านข่าวภาษาอังกฤษได้คล่องเหมือนอ่านข่าวภาษาไทย
    ผมสรุปอย่างนี้เพราะมี 2 บทความในเว็บนี้ที่ท่านผู้อ่านเข้าไปอ่านมากทีเดียว
  soundex: >-
    รถ

    รด

    รส