tokenisation_algorithms:
  - newmm
  - longest
text_samples:
  short: >-
    คนที่ฝึกภาษาอังกฤษ แม้ว่าต่างคนจะต่างความต้องการ  แต่อย่างหนึ่งที่ดูจะเหมือนกัน คือ
    อยากอ่านข่าวภาษาอังกฤษได้คล่องเหมือนอ่านข่าวภาษาไทย
    ผมสรุปอย่างนี้เพราะมี 2 บทความในเว็บนี้ที่ท่านผู้อ่านเข้าไปอ่านมากทีเดียว
  soundex: >-
    รถ

    รด

    รส
  news: >-
    “อนุทิน” บอกอย่าห่วงปมสอบ “เสี่ยโต้ง” ขอกันยังมากกว่า
    เมื่อเวลา 08.20 น. วันที่ 19 มิถุนายน ที่หอประชุมใหญ่ทีโอที ถ.แจ้งวัฒนะ นายอนุทิน ชาญวีรกูล หัวหน้าพรรคภูมิใจไทย
    ให้สัมภาษณ์ถึงความคืบหน้า การสอบสวนกรณีนายสิริพงศ์ อังคสกุลเกียรติ ส.ส.ศรีสะเกษ
    ที่โหวตสวนมติพรรคในการเลือกนายกฯ หัวหน้าพรรคภูมิใจไทย กล่าวว่า ยังไม่คืบหน้า อย่าไปกังวล
    ทุกอย่างทำตามระเบียบพรรค เรื่องแค่นี้ขอกันกินยังมากกว่า ทั้งนี้ ตนไม่ทราบว่านายสิริพงศ์
    ได้ชี้แจงต่อคณะกรรมการสอบสวนของพรรคแล้วหรือไม่ แต่ได้โทรศัพท์คุยกันก็ยังเป็นปกติ
    ไม่มีปัญหาเป็นเอกสิทธิ์ของส.ส.ก็ต้องเคารพ เพราะเขาใช้เอกสิทธิ์ของเขา
    ส่วนมติพรรคก็เป็นเรื่องของมติพรรค อย่างไรก็ตาม คงไม่มีการกำชับส.ส.ของพรรคในเรื่องนี้
    เพราะทุกคนมีวุฒิภาวะ และคงพูดกันรู้เรื่อง แต่กรณีที่เกิดขึ้นในครั้งที่ผ่านมาอาจจะเผลอไป